Repository vmware/splinterdb, pull requests merged in 2023-04, with the labels that each got.

#562 (#561) Fix routing_filter_prefetch() to account for page-size while computing next page-address.
  src/btree.c
  src/clockcache.c
  src/routing_filter.c
  tests/unit/splinterdb_stress_test.c
Labels: cla-not-required

#549 (#548) Change typedef of bool from int32 to 1-byte 'unsigned char'.
  include/splinterdb/data.h
  include/splinterdb/platform_linux/public_platform.h
  include/splinterdb/public_util.h
  include/splinterdb/splinterdb.h
  src/btree.c
  src/data_internal.c
  src/platform_linux/platform.h
  src/routing_filter.c
  src/routing_filter.h
  src/splinterdb.c
  tests/functional/splinter_test.c
  tests/functional/ycsb_test.c
Labels: cla-not-required

#566 CI: Bump timeout from 2h to 3h. shmem-tests cause debug test runs to take longer.
  ci/steps.lib.yml
Labels: cla-not-required

#572 CI requires an "ok-to-test" label before running PRs
  ci/pipeline.yml
Labels: cla-not-required

#573 Update CONTRIBUTING.md to describe ok-to-test PR label
  CONTRIBUTING.md
Labels: cla-not-required, ok-to-test

#496 Copy-on-write Trunk
  src/allocator.h
  src/clockcache.c
  src/data_internal.c
  src/memtable.c
  src/memtable.h
  src/platform_linux/platform.c
  src/platform_linux/platform_types.h
  src/trunk.c
  src/trunk.h
  tests/config.c
  tests/functional/btree_test.c
  tests/functional/splinter_test.c
Labels: cla-not-required, ok-to-test

#547 (#546) Fix the segmentation fault after splinterdb_stats_reset()
  src/trunk.c
Labels: bug, ok-to-test

#575 fix next_req node-split bug in trunk
  src/trunk.c
Labels: cla-not-required, ok-to-test

#574 Robj/memtable race fix
  src/memtable.c
  src/memtable.h
  src/platform_linux/platform.c
  src/platform_linux/platform_types.h
  src/trunk.c
  tests/functional/btree_test.c
Labels: cla-not-required, ok-to-test
